baseURL = 'https://ads-cmgp.cz/'
title = "Autonomní debatní spolek CMGP"
languageCode = 'cs'
defaultContentLanguage = 'cs'
[output]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true